FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY raspberry_buzzer ./raspberry_buzzer
COPY pyproject.toml ./

RUN pip install --no-cache-dir -e .[gui]

EXPOSE 8501

CMD ["streamlit", "run", "raspberry_buzzer/gui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
