FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY cli/requirements.txt ./requirements.txt
COPY src ./src
COPY cli/cli.py ./cli.py

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "cli.py"]
